/**
 * Nouveautés du site et de l'addon (bouton « Nouveautés » de la barre du haut), écrites pour les joueurs.
 * Ajouter les nouvelles en tête, avec un numéro `n` plus grand que le précédent (sert à savoir ce qui est déjà lu).
 */
export interface NewsItem { n: number; date: string; kind: "site" | "addon" | "bot"; version?: string; title: string; text: string }

export const NEWS: NewsItem[] = [
  { n: 30, date: "2026-10-06", kind: "site", title: "Roster, la version pour WoW Retail, se prépare",
    text: "Le site a maintenant une page d'accueil publique, et une deuxième adresse arrive : Roster (roster.sleyvazh.fr), les mêmes outils pour les guildes de WoW Retail. Ton compte y marche déjà : même e-mail, même mot de passe (connexion à faire une fois sur chaque adresse). Persos et groupes restent séparés par jeu. Le bot Discord sert les deux sites, avec /roster-lier pour les groupes Roster." },
  { n: 29, date: "2026-10-06", kind: "addon", version: "1.1", title: "Raid d'essai corrigé",
    text: "Les objets s'affichent avec leur nom du jeu (plus de « objet 16901 »), le gagnant d'un jet est marqué par l'étoile des marqueurs de raid, et un /roll compte même avec le nom de famille de Forever (« John Poutre »). Sur le site, un perso ouvert depuis la fiche d'un joueur s'affiche maintenant dans le groupe, plus dans Mes persos." },
  { n: 28, date: "2026-10-06", kind: "addon", version: "1.1", title: "Raid d'essai : tout essayer seul",
    text: "/fr test (ou « Raid d'essai » dans l'onglet En raid, hors groupe) lance un raid fictif avec 9 joueurs simulés : versions de l'addon, appel aux consommables, fiche du boss en ciblant n'importe quel PNJ, butin en soft reserve (bonus SR+, égalité, MS puis OS, jet libre) et au conseil (réponses, votes). Ton propre /roll compte. Rien ne part au site ni au chat du raid. Les rôles s'affichent aussi avec les icônes du jeu." },
  { n: 27, date: "2026-10-06", kind: "site", title: "Icônes de rôle du jeu",
    text: "Tank, Heal et DPS s'affichent avec les icônes du jeu dans les inscriptions, la compo, les besoins, les cartes de raid et les groupes ; le nom du rôle reste au survol. L'annonce Discord les utilise aussi." },
  { n: 26, date: "2026-10-05", kind: "addon", version: "1.0", title: "Fiches de boss et consommables en jeu",
    text: "En ciblant un boss avant le pull, l'addon affiche ta tâche et le reste de la fiche ; le chef peut l'annoncer en /raid. Onglet « En raid » : « Appel aux consommables » demande à l'addon de chacun ce qu'il a dans ses sacs, puis « Annoncer les manques ». Tu y vois aussi qui a l'addon dans le raid." },
  { n: 25, date: "2026-10-05", kind: "addon", version: "1.0", title: "Le butin se distribue en jeu",
    text: "Maître du butin : en ouvrant un corps, l'addon propose « Jets SR » (seuls ceux qui ont réservé lancent, bonus SR+ ajouté), « Jets MS / OS », « Jet libre » ou « Conseil » (chacun répond BiS, Upgrade, Off-Spec, Transmo, le conseil vote). Égalité : seuls les ex æquo relancent. Un objet gardé passe dans « Objets à remettre », avec un bouton pour l'échanger. Les réservations s'affichent aussi au survol des objets." },
  { n: 24, date: "2026-10-05", kind: "site", title: "Onglet Préparation : consommables et fiches de boss",
    text: "Sur la page du raid, les officiers demandent des consommables (pour tout le monde, les tanks, les heals ou un type de DPS) et voient qui est prêt. Ils remplissent aussi une fiche par boss : qui tanke, qui soigne, qui décurse, avec des consignes. Tout est repris au raid suivant du même nom. En loot council, le conseil se choisit raid par raid (onglet Butin)." },
  { n: 23, date: "2026-10-05", kind: "site", title: "Déclare tes absences à l'avance",
    text: "Sur Mes persos, « + Déclarer une absence » : une période (du … au …) ou chaque semaine (« jamais le vendredi »). Les raids de ces jours où tu n'as pas répondu passent en « Absent » dans tous tes groupes, même ceux créés plus tard ; une réponse déjà donnée ne change pas. Le motif est facultatif et tu choisis qui le voit. Les membres du groupe ont aussi leur taux de présence dans l'onglet Membres." },
  { n: 22, date: "2026-10-05", kind: "bot", title: "Les commandes d'artisanat dans un salon Discord",
    text: "Un officier lie un salon aux commandes (Administration → Discord, puis /forever-lier dans le salon) : le bot y poste chaque commande avec les artisans qui savent la faire, et un bouton « Je m'en charge ». Le message suit la commande jusqu'à ce qu'elle soit faite." },
  { n: 21, date: "2026-10-05", kind: "site", title: "Commande une fabrication aux artisans du groupe",
    text: "Onglet Artisans : « Commander » sur une recette (ou cherche-la), choisis la quantité et coche les composants que tu fournis. Les artisans qui la connaissent la voient, l'un d'eux la prend puis la marque faite. Sur ta fiche de perso, l'import de l'addon devient une ligne de synchro : tout passe par Ctrl+V, avec « Choisir quoi importer »." },
  { n: 20, date: "2026-10-05", kind: "site", title: "Un site plus simple : raids, persos par groupe, page du raid en onglets",
    text: "Onglet Raids : la liste d'abord (à venir / passés), « + Nouveau raid » ouvre un formulaire court avec les jours en boutons et l'heure en 24 h ; « Chaque semaine » en fait un raid récurrent. Mes persos se range par groupe : chaque perso a un groupe et tu choisis ton main sur sa fiche. La page du raid passe en onglets (Compo, Inscriptions, Butin, Bilan, Réglages). Et l'import de l'addon vide les emplacements retirés en jeu, main gauche comprise sous une arme à deux mains." },
  { n: 19, date: "2026-10-05", kind: "site", title: "Spé « Fury Tank » retirée",
    text: "Elle n'existera pas sur Forever : les guerriers qui l'avaient passent en Protection (ils restent tanks dans les compos). Les chamans ont aussi leurs icônes de spé, dont Enhancement Tank." },
  { n: 18, date: "2026-10-05", kind: "bot", title: "Le bot relance ceux qui n'ont pas répondu",
    text: "48 h avant le raid (24 ou 72 h au choix), le bot écrit en privé aux membres qui n'ont pas répondu : un clic sur Présent, Peut-être ou Absent suffit. Les officiers reçoivent la liste, peuvent relancer à la main depuis la page du raid, et « Demander » dans l'encart Besoins invite un joueur précis à venir avec tel perso." },
  { n: 17, date: "2026-10-05", kind: "site", title: "Raids à 10, 20 ou 40, compo assistée, banc équitable, fiche joueur",
    text: "Choisis le format du raid : la compo vise les bons rôles. L'encart Besoins dit ce qui manque et propose qui peut combler (inscrits, off-spec, alts). Trop d'inscrits ? Le site propose de mettre sur le banc ceux qui y sont allés le moins. Et un clic sur un membre ouvre sa fiche : persos, présence, butin." },
  { n: 16, date: "2026-10-05", kind: "site", title: "Butin : mode choisi à la création du raid, soft reserve",
    text: "En créant un raid, choisis le butin : Journal, Loot council ou Soft reserve. En soft reserve, chacun réserve ses objets sur la page du raid (bonus SR+ si on réserve le même objet raid après raid). Le site apprend le butin de chaque raid grâce aux bilans de l'addon." },
  { n: 15, date: "2026-10-05", kind: "site", title: "Ton main et tes alts dans chaque groupe",
    text: "Dans l'onglet Personnages d'un groupe, choisis les persos que tu y joues et ton main (★). Affiche les mains seuls, avec les alts, séparés, ou par joueur. Ton main est proposé en premier pour t'inscrire aux raids." },
  { n: 14, date: "2026-10-05", kind: "bot", title: "Donne ton avis à ton équipe, signé ou anonyme",
    text: "Sur Discord, /feedback (ou le bouton « Donner mon avis » du salon prévu) : le bot t'écrit en privé, tu écris ton avis, puis tu choisis de l'envoyer signé ou anonyme. L'équipe peut te répondre, même anonyme. Marche aussi sur un serveur qui n'utilise pas le site." },
  { n: 13, date: "2026-10-04", kind: "addon", version: "0.9", title: "L'addon habillé comme le site",
    text: "Dans l'onglet Options, choisis l'habillage « Site » : fond sombre, liserés dorés, titres du site et onglets en haut. « Forever (jeu) » garde l'interface du jeu. Aussi avec /fr habillage." },
  { n: 12, date: "2026-10-04", kind: "addon", version: "0.8.1", title: "Inscriptions en jeu aux couleurs du site",
    text: "Présent en vert, En retard en orange, Peut-être en gris, Absent en rouge : ta réponse actuelle est surlignée, dans l'onglet Raids comme dans « Tu viens ? »." },
  { n: 11, date: "2026-10-04", kind: "addon", version: "0.8", title: "Présence et butin relevés pendant les raids",
    text: "Pendant un raid prévu sur le site, l'addon note qui est là et le butin épique. Après le raid, un officier fait sa synchro : le bilan s'affiche sur la page du raid, le BiS reçu est coché sur la fiche, et l'onglet « Présence & butin » du groupe fait les comptes." },
  { n: 10, date: "2026-10-04", kind: "site", title: "Liste des persos du groupe remise d'aplomb",
    text: "Colonnes alignées, noms longs sur une ligne, persos à configurer en fin de liste, et un affichage propre sur téléphone." },
  { n: 9, date: "2026-10-04", kind: "site", title: "Page Groupes plus parlante",
    text: "Chaque groupe montre son prochain raid et ta réponse, le nombre de raids à venir, le roster par rôle et des raccourcis vers ses onglets." },
  { n: 8, date: "2026-10-03", kind: "addon", version: "0.7", title: "Un onglet Options en jeu",
    text: "Choisis ta touche de synchro en appuyant dessus, masque le bouton de la minicarte, coupe le rappel de raid, retire de l'export un perso supprimé." },
  { n: 7, date: "2026-10-03", kind: "site", title: "Ton prochain raid en haut de Mes persos",
    text: "Inscris-toi en un clic (Présent, Peut-être, Absent). « À faire » déplie les autres raids de la semaine et les fiches à compléter." },
  { n: 6, date: "2026-10-03", kind: "addon", version: "0.6", title: "« Tu viens ? » à la connexion",
    text: "Un raid dans les 24 h sans réponse ? L'addon te le demande quand tu te connectes." },
  { n: 5, date: "2026-10-03", kind: "site", title: "Les onglets gardés dans l'adresse",
    text: "Le retour arrière et le rechargement restent sur l'onglet ouvert, et tu peux envoyer le lien direct d'un onglet (par exemple les Artisans de ton groupe)." },
  { n: 4, date: "2026-10-02", kind: "addon", version: "0.5", title: "Synchro rapide : une touche, une case",
    text: "Ta touche ouvre une petite fenêtre : Ctrl+C pour envoyer tes persos, Ctrl+V pour charger les données du site. Sur le site, Ctrl+V sur n'importe quelle page." },
  { n: 3, date: "2026-10-02", kind: "addon", version: "0.4", title: "L'addon aux couleurs de Forever",
    text: "Fenêtre, onglets et bordures reprennent l'interface du jeu." },
  { n: 2, date: "2026-10-02", kind: "addon", version: "0.2", title: "Patrons et BiS suivis en jeu",
    text: "Infobulles « Recherché par », « Connu par », « BiS de », liste de tes sacs avec Annoncer, et alerte quand tu ramasses un objet suivi." },
  { n: 1, date: "2026-10-02", kind: "site", title: "Les vrais arbres de talents de Forever",
    text: "Les talents de ta fiche suivent les arbres du client Forever, et l'addon les lit directement en jeu." },
];
